apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80            # External port
    targetPort: 5000     # Port on the pod where Flask is running
    nodePort: 31000      # NodePort to use (you can specify any available port in the range 30000-32767)
  type: NodePort

