Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end
  config.vm.network "forwarded_port", guest: 5001, host: 5002
  config.vm.provision "file", source: "./flask_blog", destination: "/home/vagrant/flask_blog"
  config.vm.provision "file", source: "./requirements.txt", destination: "/home/vagrant/"
  config.vm.provision "shell", inline: "echo 'First provisioner'"
  config.vm.provision "shell", inline: "echo 'Second provisioner'"
  config.vm.provision "shell" do |s| 
    s.inline = <<-SHELL
      apt-get update
      apt-get install -y python3-pip
      pip3 install --no-cache-dir -r requirements.txt
      nohup flask run 
    SHELL
    s.env = {"FLASK_ENV" => "development",
             "FLASK_APP" => "flask_blog/app",
             "FLASK_RUN_PORT" => "5001",
             "FLASK_RUN_HOST" => "0.0.0.0"}
  end
end