version: 2.1

jobs:
  # Job for building and testing the frontend (React)
  frontend-build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-dependencies-{{ checksum "chat-app/chat-frontend/package.json" }}
            - frontend-dependencies-
      - run:
          name: Install Frontend Dependencies
          command: cd chat-app/chat-frontend && npm install
      - save_cache:
          paths:
            - chat-app/chat-frontend/node_modules
          key: frontend-dependencies-{{ checksum "chat-app/chat-frontend/package.json" }}
      - run:
          name: Run Frontend Tests
          command: cd chat-app/chat-frontend && npm test
      - run:
          name: Build Frontend
          command: cd chat-app/chat-frontend && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - chat-app/chat-frontend/build
            - chat-app/chat-frontend/node_modules

  # Job for building and testing the backend (Dropwizard)
  backend-build:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-dependencies-{{ checksum "chat-app/chat-backend/pom.xml" }}
            - backend-dependencies-
      - run:
          name: Install Backend Dependencies
          command: cd chat-app/chat-backend && mvn install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: backend-dependencies-{{ checksum "chat-app/chat-backend/pom.xml" }}
      - run:
          name: Run Backend Tests
          command: cd chat-app/chat-backend && mvn test
      - run:
          name: Build Backend
          command: cd chat-app/chat-backend && mvn package
      - persist_to_workspace:
          root: .
          paths:
            - chat-app/chat-backend/target

  # Job for deployment or packaging
  deploy:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Prepare Artifacts for Deployment
          command: |
            echo "Packaging frontend and backend for deployment"
            ls -la chat-app/chat-frontend/build
            ls -la chat-app/chat-backend/target
            # Add your deployment commands here

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - frontend-build
      - backend-build
      - deploy:
          requires:
            - frontend-build
            - backend-build
          filters:
            branches:
              only: devops_assignment