version: 2.1

jobs:
  # Job for building and testing the frontend (React)
  frontend-build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-dependencies-{{ checksum "chat-app/chat-frontend/package.json" }}
            - frontend-dependencies-
      - run:
          name: Install Frontend Dependencies
          command: cd chat-app/chat-frontend && npm install
      - save_cache:
          paths:
            - chat-app/chat-frontend/node_modules
          key: frontend-dependencies-{{ checksum "chat-app/chat-frontend/package.json" }}
      - run:
          name: Run Frontend Tests
          command: cd chat-app/chat-frontend && npm test
      - run:
          name: Build Frontend
          command: cd chat-app/chat-frontend && npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - chat-app/chat-frontend

  # Job for building and testing the backend (Dropwizard)
  backend-build:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-dependencies-{{ checksum "chat-app/chat-backend/pom.xml" }}
            - backend-dependencies-
      - run:
          name: Install Backend Dependencies
          command: cd chat-app/chat-backend && mvn install -DskipTests
      - save_cache:
          paths:
            - chat-app/chat-backend/.m2
          key: backend-dependencies-{{ checksum "chat-app/chat-backend/pom.xml" }}
      - run:
          name: Run Backend Tests
          command: cd chat-app/chat-backend && mvn test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - chat-app/chat-backend

  # Job for deployment or packaging (if needed)
  deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Prepare Artifacts for Deployment
          command: |
            echo "Packaging frontend and backend for deployment"
            ls /workspace/chat-app/chat-frontend
            ls /workspace/chat-app/chat-backend
            # Include additional deployment commands if needed

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - frontend-build:
      - backend-build:
      - deploy:
          requires:
            - frontend-build
            - backend-build
          filters:
            branches:
              only: devops_assignment
