version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo/chat-app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "chat-app/chat-frontend/package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            cd chat-app/chat-frontend && npm install
            cd ../chat-backend && npm install
      - save_cache:
          paths:
            - chat-app/chat-frontend/node_modules
            - chat-app/chat-backend/node_modules
          key: v1-dependencies-{{ checksum "chat-app/chat-frontend/package.json" }}
      - run:
          name: Run Frontend Tests
          command: cd chat-app/chat-frontend && npm test
      - run:
          name: Run Backend Tests
          command: cd chat-app/chat-backend && npm test
      - run:
          name: Build Frontend
          command: cd chat-app/chat-frontend && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - chat-app

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Prepare for Deployment
          command: |
            echo "Building application and saving artifacts for local deployment"
            cd /workspace/chat-app/chat-frontend && npm install && npm run build
            cd /workspace/chat-app/chat-backend && npm install

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: devops_assignment
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: devops_assignment
