version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - FLASK_RUN_PORT=5001
      - FLASK_RUN_HOST=0.0.0.0
  # test:
  #   build: .
  #   command: echo "Tests passed!"
